### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by gedw99** [xitongsys/guery#8]
this project looks really useful.

i suggest you add some examples. Or maybe you have some already ?

**Comment by xitongsys** [comment]
hi, @gedw99 
thanks your suggestion and i will add more introduction and examples.
For now you can see the Makefile. And the configuration file example is in config/config.json.
The major part is the hive config:
```
    "HiveConnectorConfigs":{
	"hive.*.*":{
	    "Host":"127.0.0.1:3306",
	    "DB":"hive",
	    "User":"hive",
	    "Password":"hive"
	}
    }```
Host is the hive metastore address(MySql).
